language: node_js
node_js:
- node
cache:
  apt: true
  directories:
  - node_modules
env:
- SERVER_IP_ADDRESS=8.129.231.174
addons:
  ssh_known_hosts:
  - 8.129.231.174
script:
- npm install
after_script:
- npm run build
before_install:
